// app/(auth)/layout.tsx
/*export default function AuthLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                {children}
            <div>Авторизация</div>
            </body>
        </html>
    );
}*/

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Universal Motors",
    description: "Generated by create next app",
    icons: {
        icon: "/umico.png",
    },
};
export default function AuthLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
                <div>Авторизация</div>
            </body>
        </html>
    );
}